<?php

/**
 * @file
 *   Hook implementations and general functions.
 */
use Drupal\payment_form\Entity\Payment\PaymentForm;

/**
 * Implements hook_entity_type_alter().
 */
function payment_form_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface $entity_type */
  $entity_type = $entity_types['payment'];
  $entity_type->setFormClass('payment_form', PaymentForm::class);
}

/**
 * Implements hook_entity_extra_field_info().
 */
function payment_form_entity_extra_field_info() {
  return \Drupal::service('payment_form.hook.entity_extra_field_info')->invoke();
}
