commerce_checkout.commerce_checkout_pane.order_fields:*:
  type: commerce_checkout_pane_configuration
  mapping:
    wrapper_element:
      type: string
      label: 'Wrapper element'
    display_label:
      type: string
      label: 'Display label'
